name: TEST

# on:
#   push:
#     branches-ignore:
#       - gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up cflisp and CMake, lcov
      run: |
        sudo apt update
        sudo apt install -y cmake lcov
      shell: bash

    - name: Build project with CMake and Test with coverage
      run: |
        rm -rf build
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON
        cmake --build build
        ulimit -s 65536
        build/unit_test
        cmake --build build --target coverage
      shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-MacOS:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up cflisp and CMake
      run: |
        brew update
        brew install cmake
      shell: bash

    - name: Build project with CMake and Test
      run: |
        rm -rf build
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
        build/unit_test
      shell: bash

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up cflisp and CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: powershell

    - name: Build project with CMake and Test
      run: |
        rmdir /s /q build
        cmake -B build
        cmake --build build --config Debug
        build\Debug\unit_test.exe
      shell: cmd
